/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GraphicInterfaces;

/**
 *
 * @author Posilandia
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        addFriend = new javax.swing.JButton();
        deleteFriend = new javax.swing.JButton();
        save = new javax.swing.JButton();
        showGraph = new javax.swing.JButton();
        loadFile = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addFriend.setText("Agregar Amigo");
        addFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFriendActionPerformed(evt);
            }
        });
        getContentPane().add(addFriend, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, 40));

        deleteFriend.setText("Eliminar Amigo");
        deleteFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFriendActionPerformed(evt);
            }
        });
        getContentPane().add(deleteFriend, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, 40));

        save.setText("Guardar");
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 160, 40));

        showGraph.setText("Mostrar Grafo");
        getContentPane().add(showGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 160, 40));

        loadFile.setText("Cargar Archivo");
        getContentPane().add(loadFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFriendActionPerformed
        // TODO add your handling code here:
        AddFriend ventana1 = new AddFriend();
        ventana1.setVisible(true);
    }//GEN-LAST:event_addFriendActionPerformed

    private void deleteFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFriendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteFriendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFriend;
    private javax.swing.JButton deleteFriend;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton loadFile;
    private javax.swing.JButton save;
    private javax.swing.JButton showGraph;
    // End of variables declaration//GEN-END:variables
}
